version: "3.3"

services:
  # Backend Server
  api-server:
    build:
      context: .
    ports:
      - 8131:8131
    container_name: 13_api-server
    network_mode: bridge
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sqlite-db:/app/db

  # Frontend Server
  frontend-server:
    build:
      context: ./frontend
    ports:
      - 8130:3000
    container_name: 13_frontend-server
    network_mode: bridge
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  sqlite-db:
