name: Docker Hub Deployment

on:
  push:
    tags:
      - "v*"

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish API Server to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: kahkoii/eti-asgt-api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          default_branch: main

      - name: Publish Frontend Server to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: kahkoii/eti-asgt-frontend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: frontend
          default_branch: main
